Create ListaEncadeada.c
kelvins/Algoritmos-e-Estruturas-de-Dados pull request #120
Opened 2022-03-11 16:09 UTC by CleberSalustiano

Acabei fechando o último pull request sem querer aqui. Recriando o arquivo com as devidas alterações

2022-03-13 15:15 UTC, kelvins requested changes
Obrigado pela contribuição @CleberSalustiano.

Poderia por favor incluir o link para o seu algoritmo no README?

2022-03-13 15:15 UTC, kelvins commented on src/c/ListaEncadeada.c
> +    return NULL;
Como espera-se que a função `infoLista` retorne um inteiro, esse valor nulo está sendo convertido para zero, ou seja, se o usuário passar um índice menor que 0 ou maior que o tamanho da lista a função vai retornar o valor zero, o que está incorreto. O ideal nesse caso (na minha opinião) seria fazer com que a função `infoLista` retornasse um ponteiro para o nó da lista e o próprio usuário poderia verificar se o ponteiro é nulo ou não e extrair o valor. Isso evitaria de retornar um valor incorreto. No caso de incluir essa alteração é preciso alterar todas as chamadas de `infoLIsta` para verificar o ponteiro.

(note que ao compilar o código ele apresenta esse warning)

2022-03-13 15:15 UTC, kelvins commented on src/c/ListaEncadeada.c
> +  if((i < 0) || (i > tam) || (tam == 0)) return NULL;
Este caso é igual ao do `infoLista` mas como aqui estamos preocupados em remover um valor da lista talvez fosse mais fácil alterar a função `removeLista` para `void` e simplesmente não retornar nada.

2022-03-14 16:12 UTC, CleberSalustiano commented on src/c/ListaEncadeada.c
> +  if((i < 0) || (i > tam) || (tam == 0)) return NULL;
Beleza, alterei para não precisar retornar nada.

2022-03-14 23:49 UTC, kelvins commented
Boa, valeu @CleberSalustiano

2022-03-14 23:49 UTC, merged