Added TwoSum Algorithm in C and updated readme.md
kelvins/Algoritmos-e-Estruturas-de-Dados pull request #164
Opened 2023-09-14 16:16 UTC by ricardocarva

Added TwoSum Algorithm in C and updated readme.md

2023-09-15 23:57 UTC, kelvins requested changes
Valeu pela contrib @ricardocarva, deixei alguns comentários e sugestões.

2023-09-15 23:57 UTC, kelvins commented on README.md
> +                <a href="/src/cpp/Palindrome.cpp">
Acredito que essa alteração é do outro PR e entrou por engano nesse.

2023-09-15 23:57 UTC, kelvins commented on src/c/TwoSum.c
> +    	printf("The two numbers that add up to %d are: %d and %d\n", target, nums[0], nums[1]);
O resultado aqui foi 2 e 11, quando deveria ser 2 e 7.
Acredito que os indices deveriam ser algo como `nums[result[0]]` e `nums[result[1]]`.

2023-09-15 23:57 UTC, kelvins commented on src/c/TwoSum.c
> +	}
```suggestion
    }
```

2023-09-15 23:57 UTC, kelvins commented on src/c/TwoSum.c
> +    int returnSize = 0;
Esse `returnSize` é utilizado para algo? Se não podemos removê-lo.

2023-09-15 23:57 UTC, kelvins commented on src/c/TwoSum.c
> +        for( int j=i+1;j<numsSize;j++)
```suggestion
        for(int j=i+1;j<numsSize;j++)
```

2023-09-15 23:57 UTC, kelvins commented on src/c/TwoSum.c
> +                int * x =(int*) malloc(2*sizeof(int));
```suggestion
                int* x = (int*) malloc(2*sizeof(int));
```

2023-09-16 04:10 UTC, ricardocarva commented on README.md
> +                <a href="/src/cpp/Palindrome.cpp">
Isso mesmo. Foi por engano.

2023-09-16 04:10 UTC, ricardocarva commented on src/c/TwoSum.c
> +    	printf("The two numbers that add up to %d are: %d and %d\n", target, nums[0], nums[1]);
Correto. Vamos atualizar eles para nums[result[0]] e nums[result[1]] e fica tudo certo.

2023-09-16 04:11 UTC, ricardocarva commented on src/c/TwoSum.c
> +    int returnSize = 0;
Sim, é desnecessario. Podemos removê-lo.

2023-09-16 19:13 UTC, ricardocarva commented on src/c/TwoSum.c
> +    int returnSize = 0;
Removido

2023-09-16 19:13 UTC, ricardocarva commented on src/c/TwoSum.c
> +    	printf("The two numbers that add up to %d are: %d and %d\n", target, nums[0], nums[1]);
Atualizado

2023-09-16 19:14 UTC, ricardocarva commented on README.md
> +                <a href="/src/cpp/Palindrome.cpp">
Acho que agora que o outro PR foi aceito, esta tudo bem manter assim? Me avisa qualquer coisa, por favor?

2023-09-16 19:14 UTC, ricardocarva commented
Acredito que agora esta tudo bem?

2023-09-17 00:32 UTC, kelvins approved these changes

2023-09-17 00:33 UTC, merged