Algoritmo de busca reacursiva em C e alteração do README.
kelvins/Algoritmos-e-Estruturas-de-Dados pull request #81
Opened 2020-11-24 17:31 UTC by biancaguzenski

2020-11-28 11:38 UTC, kelvins reviewed
Obrigado pela contrib @biancaguzenski.

Você pode atualizar sua branch e resolver o conflito do README por favor?

2020-11-28 11:38 UTC, kelvins commented on README.md
> +| [Busca Sequencial Recursiva][8]          | [C/C++](/src/c/BuscaSequencialRecursiva.c) | Java | [Python](./src/python/busca_sequencial_recursiva.py) | Go | [Ruby](src/ruby/Busca_Sequencial_Recursiva
```suggestion
| [Busca Sequencial Recursiva][8]          | [C/C++](./src/c/BuscaSequencialRecursiva.c) | Java | [Python](./src/python/busca_sequencial_recursiva.py) | Go | [Ruby](src/ruby/Busca_Sequencial_Recursiva.rb) | [JS](./src/javascript/RecursiveLinearSearch.js) |  Pascal | Swift | Rust |
```

2020-11-28 11:38 UTC, kelvins commented on src/c/BuscaSequencialRecursiva.c
> +    size_t n = sizeof(vetor) / sizeof(vetor[0]);
Na verdade essa definição precisa ficar no `main` e passar o `n` como argumento para a função `buscaSequencialRecursiva` (https://github.com/kelvins/Algoritmos-e-Estruturas-de-Dados/pull/80#discussion_r531232139)

2020-11-28 11:38 UTC, kelvins commented on src/c/BuscaSequencialRecursiva.c
> +    else if (i == n)
Temos que comparar o `i == n` primeiro, caso contrário na última iteração vamos acessar uma posição inválida do array `vetor[i]`. Por exemplo:
```python
    if (i == n)
    {
        return -1;
    }
    else if (vetor[i] == buscado)
    {
        return i;
    } 
    return buscaSequencialRecursiva(vetor, i+1, buscado);
```
Note que também precisamos definir um `return` antes do `buscaSequencialRecursiva` :point_up:

2020-11-28 11:38 UTC, kelvins commented on src/c/BuscaSequencialRecursiva.c
> +    buscaSequencialRecursiva(a, 0, 10);
```suggestion
    printf("Valor %d no índice %d\n", 10, buscaSequencialRecursiva(a, 0, 10));
```

2020-12-07 18:06 UTC, biancaguzenski commented
@kelvins Obrigada pelos comentários! Desculpe a demora, as modificações foram feitas. Obrigada por esclarecer os erros! Abraços

2020-12-07 19:52 UTC, kelvins requested changes
@biancaguzenski obrigado pelas alterações, segue só mais dois pontos.

2020-12-07 19:52 UTC, kelvins commented on README.md
> +| [Busca Sequencial][7]                    | [C/C++](/src/c/BuscaSequencial.c) | Java | [Python](./src/python/busca_sequencial.py) | Go | [Ruby](./src/ruby/BuscaSequencial.rb) | [JS](./src/javascript
Para evitar de quebrar o CI que utiliza um validador de links:

```suggestion
| [Busca Sequencial][7]                    | [C/C++](./src/c/BuscaSequencial.c) | Java | [Python](./src/python/busca_sequencial.py) | Go | [Ruby](./src/ruby/BuscaSequencial.rb) | [JS](./src/javascript/BuscaLinear.js) |  Pascal | Swift | Rust |
```

2020-12-07 19:52 UTC, kelvins commented on src/c/BuscaSequencialRecursiva.c
> +        buscaSequencialRecursiva(vetor, i+1, buscado, size);
A chamada recursiva precisa ser retornada:

```suggestion
        return buscaSequencialRecursiva(vetor, i+1, buscado, size);
```

2020-12-07 20:05 UTC, biancaguzenski commented
@kelvins Alterações feitas!

2020-12-07 20:06 UTC, kelvins approved these changes

2020-12-07 20:06 UTC, merged